language: node_js
node_js: lts/*
os: osx
osx_image: xcode9.3

cache:
  directories:
    - node_modules

before_script:
  - scripts/update-submodule
script:
  - npm run build
after_script:
  - scripts/push-submodule-update

before_deploy: scripts/build-release
deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GH_TOKEN # Set in travis-ci.org dashboard
    file: refined-github.safariextz
    on:
      tags: true
  - provider: releases
    skip_cleanup: true
    api_key: $GH_TOKEN # Set in travis-ci.org dashboard
    file: refined-github.safariextz
    on:
      # Set to deploy on: cron with recent commits
      branch: master
      condition: $(npm run can-release --silent)
after_deploy: scripts/update-manifest
