language: node_js
node_js: lts/*
os: osx
osx_image: xcode9.3

cache:
  directories:
    - node_modules

before_script:
  - scripts/update-submodule
script:
  - npm run build

before_deploy: scripts/build-release
deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $GH_TOKEN # Set in travis-ci.org dashboard
    file: refined-github.safariextz
    on:
      tags: true
after_deploy: scripts/update-manifest
